const Models = Object.freeze({
  '01': 'Nota Fiscal',
  '02': 'Nota Fiscal de Venda a Consumidor',
  '04': 'Nota Fiscal de Produtor',
  '06': 'Nota Fiscal/Conta de Energia Elétrica',
  '07': 'Nota Fiscal de Serviço de Transporte',
  '08': 'Conhecimento de Transporte Rodoviário de Cargas',
  '09': 'Conhecimento de Transporte Aquaviário de Cargas',
  '10': 'Conhecimento Aéreo',
  '11': 'Conhecimento de Transporte Ferroviário de Cargas',
  '13': 'Bilhete de Passagem Rodoviário',
  '14': 'Bilhete de Passagem Aquaviário',
  '15': 'Bilhete de Passagem e Nota de Bagagem',
  '16': 'Bilhete de Passagem Ferroviário',
  '17': 'Despacho de Transporte',
  '18': 'Resumo Movimento Diário',
  '20': 'Ordem de Coleta de Carga',
  '21': 'Nota Fiscal de Serviço de Comunicação',
  '22': 'Nota Fiscal de Serviço de Telecomunicações',
  '23': 'GNRE',
  '24': 'Autorização de Carregamento e Transporte',
  '25': 'Manifesto de Carga Eletrônico (MFC-e)',
  '26': 'Conhecimento de Transporte Multimodal de Cargas (CTMC)',
  '27': 'Nota Fiscal de Transporte Ferroviário de Cargas',
  '28': 'Nota Fiscal/Conta de Fornecimento de Gás Canalizado',
  '29': 'Nota Fiscal/Conta de Fornecimento de Água Canalizada',
  '30': 'Bilhete/Recibo do Passageiro',
  '55': 'Nota Fiscal Eletrônica (NF-e)',
  '57': 'Conhecimento de Transporte Eletrônico (CT-e)',
  '58': 'Manifesto Eletrônico de Documentos Fiscais (MDF-e)',
  '59': 'Cupom Fiscal Eletrônico (CF-e/SAT)',
  '60': 'Cupom Fiscal Eletrônico (CF-e/ECF)',
  '63': 'Bilhete de Passagem Eletrônico (BP-e)',
  '65': 'Nota Fiscal de Consumidor Eletrônica (NFC-e)',
  '66': 'Nota Fiscal de Energia Elétrica Eletrônica (NF3e)',
  '67': 'Conhecimento de Transporte Eletrônico para Outros Serviços (CT-e/OS)',
  '99': 'Outros',
});

module.exports = { Models };
